# Generated by Django 4.2.4 on 2023-12-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(max_length=50)),
                ('borrower_email', models.EmailField(max_length=254, unique=True)),
                ('borrower_password', models.CharField(max_length=20)),
                ('borrower_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donar',
            fields=[
                ('donar_id', models.AutoField(primary_key=True, serialize=False)),
                ('donar_name', models.CharField(max_length=50)),
                ('donar_email', models.EmailField(max_length=254, unique=True)),
                ('donar_password', models.CharField(max_length=20)),
                ('donar_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('volunteer_id', models.AutoField(primary_key=True, serialize=False)),
                ('volunteer_name', models.CharField(max_length=50)),
                ('volunteer_email', models.EmailField(max_length=254, unique=True)),
                ('volunteer_password', models.CharField(max_length=20)),
                ('volunteer_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('vehi_id', models.AutoField(primary_key=True, serialize=False)),
                ('brief_desc', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/')),
                ('amount', models.IntegerField()),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.donar')),
            ],
        ),
        migrations.CreateModel(
            name='smallenterprise',
            fields=[
                ('enter_id', models.AutoField(primary_key=True, serialize=False)),
                ('brief_desc', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/')),
                ('amount', models.IntegerField()),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.donar')),
            ],
        ),
        migrations.CreateModel(
            name='foodandhealth',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('brief_desc', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/')),
                ('amount', models.IntegerField()),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.donar')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('brief_desc', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/')),
                ('amount', models.IntegerField()),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.donar')),
            ],
        ),
        migrations.CreateModel(
            name='agriculture',
            fields=[
                ('agri_id', models.AutoField(primary_key=True, serialize=False)),
                ('brief_desc', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='images/')),
                ('amount', models.IntegerField()),
                ('donar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.donar')),
            ],
        ),
    ]
