# Generated by Django 4.2.4 on 2023-12-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agri_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.agriculture')),
                ('edu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.education')),
                ('enter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.smallenterprise')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.foodandhealth')),
                ('vehi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.vehicles')),
            ],
        ),
    ]
