# Generated by Django 4.2.4 on 2023-12-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_borrowmodel_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmodel',
            name='borrower_img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
